# Use the official Python 2 image
FROM python:2.7

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the Python 2 script into the container
COPY main.py .

# Run the Python script
CMD ["python", "main.py"]
